Manhattan\Bundle\PostsBundle\Entity\Attachment:
    type:  entity
    table: news_attachment
    repositoryClass: Manhattan\Bundle\PostsBundle\Entity\Repository\AttachmentRepository

    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        mime_type:
            type: string
            length: 255
            nullable: true
        filename:
            type: string
            length: 255
            nullable: true
        title:
            type: string
            length: 255
            nullable: true
        description:
            type: text
            nullable: true

    manyToOne:
        post:
            targetEntity: Manhattan\Bundle\PostsBundle\Entity\Post
            inversedBy: attachments
            joinColumn:
                name: post_id
                referencedColumnName: id
                onDelete: SET NULL
        type:
            targetEntity: Manhattan\Bundle\PostsBundle\Entity\AttachmentType
            inversedBy: attachments
            joinColumn:
                name: attachment_type_id
                referencedColumnName: id
                onDelete: CASCADE

    lifecycleCallbacks:
        prePersist:
            - preUpload
            - prePersist
        preUpdate:
            - preUpdateAsset
            - preUpdate
        postPersist:
            - upload
        postUpdate:
            - replace
        preRemove:
            - storeFilenameForRemove
        postRemove:
            - removeUpload
